### ISSUE TITLE
Got an error in executiig the movie name button in telegram bot

### ISSUE THREAD

**Issue by Fashionedgroot** [SBDeveloper10/movies-downloader-bot#13]
[ERROR]	2023-04-12T07:36:34.544Z	3313f838-7c27-4108-b88b-beed901ad626	No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/var/task/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/var/runtime/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/var/runtime/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/var/runtime/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/var/task/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "./index.py", line 39, in movie_result
    s = get_movie(query.data)
  File "/var/task/movies_scraper.py", line 37, in get_movie
    link = response.json()
  File "/var/task/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by IIXII-L192** [comment]
Delete your current git, and download this again repeat all the steps in video. **DO NOT** change anything unless you know what you are doing.
